name: Pull Request

on:
  pull_request:
    branches: main

jobs:

  lint:
    name: Code Style Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: ./gradlew ktlintCheckAll

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: ./gradlew testDebugUnitTest

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: |
            **/build/test-results/
            **/build/reports/
          retention-days: 3

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: ./gradlew assembleDebug

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts
          path: |
            **/build/outputs/apk/
            **/build/outputs/bundle/
          retention-days: 3
